swagger: '2.0'
info:
  version: '0.1'
  description: 'Acesta este interfata de comunicare cu operatorii de sisteme de furnizat bonuri de ordine'
  title: Stop Cozi API
  termsOfService: 'http://stopcozi.ithub.gov.ro/terms/'
  contact:
    email: 'stopcozi@ithub.gov.ro'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: stare
    description: Operatiune de stabilire a starii unei locatii
  - name: activitate
    description: Operatiuni de comunicare a operatiunilor legate de bonuri
  - name: cautare
    description: Operatiuni de cautare a agentiilor sau serviciilor
  - name: info
    description: Operatiuni de redare a starii unui serviciu/bon 
    
schemes:
  - http
paths:
  '/ticketTracking/search/serviceSuggestions':
    get:
      tags:
        - cautare
      operationId: getServiceSuggestions
      summary: Sugereaza servicii in functie de cuvintele introduse - TBD si dupa istoria cautarilor/cautari populare
      produces:
        - application/json
      parameters:
        - name: searchText
          in: query
          required: false
          type: string
          description: string-ul dupa care face utilizatorul cautarea de servicii
        - name: limit
          in: query
          required: false
          type: integer
          format: int64
          description: numarul maxim de sugestii care vor fi returnate
      responses:
        '200':
          description: Au fost returnate servicii
          schema:
            type: array
            items:
              $ref: "#/definitions/GeneralService"
        '404':
          description: Nu s-au gasit servicii
        '409':
          description: Informatii lipsa  
  '/ticketTracking/search/services':
    get:
      tags:
        - cautare
      operationId: getServices
      summary: Reda rezultatele cautarii dupa anumite cuvinte introduse de utilizator
      produces:
        - application/json
      parameters:
        - name: searchText
          in: query
          required: false
          type: string
          description: string-ul dupa care face utilizatorul cautarea de servicii
        - name: limit
          in: query
          required: false
          type: integer
          format: int64
          description: numarul maxim de rezultate care vor fi returnate
      responses:
        '200':
          description: Au fost returnate servicii
          schema:
            type: array
            items:
              $ref: "#/definitions/GeneralService"
        '404':
          description: Nu s-au gasit servicii
        '409':
          description: Informatii lipsa    
  '/ticketTracking/search/agencySuggestionsByLocation':
    get:
      tags:
        - cautare
      operationId: getAgencySuggestions
      summary: Sugereaza agentii din apropiere care ofera serviciul selectat 
      produces:
        - application/json
      parameters:
        - name: serviceId
          in: query
          required: true
          type: integer
          format: int64
          description: serviciul pentru care se cauta agentii
        - name: searchText
          in: query
          required: false
          type: string
          description: locatia device-ului de pe care se face interogarea sau locatia introdusa de utilizator
        - name: limit
          in: query
          required: false
          type: integer
          format: int64
          description: numarul maxim de sugestii care vor fi returnate
      responses:
        '200':
          description: Au fost returnate agentii
          schema:
            type: array
            items:
              $ref: "#/definitions/Agency"
        '404':
          description: Nu s-au gasit agentii in apropiere
        '409':
          description: Informatii lipsa
  '/ticketTracking/search/{serviceId}':
    get:
      tags:
        - cautare
      operationId: getServiceAgencies
      summary: Reda agentii care ofera serviciul selectat
      produces:
        - application/json
      parameters:
        - name: serviceID
          in: path
          required: true
          type: integer
          format: int64
          description: id-ul serviciului general din tabela de mapare interna
        - name: inputString
          in: query
          required: false
          type: string
          description: cuvintele de cautare introduse de utilizator
        - name: deviceLocation
          in: query
          required: false
          type: array
          items:
            type: number
            format: float
          description: locatia device-ului de pe care se face interogarea
        - name: radius
          in: query
          required: false
          type: integer
          format: int64
          description: raza pe care sa se faca cautarea
        - name: limit
          in: query
          required: false
          type: integer
          format: int64
          description: numarul maxim de sugestii care vor fi returnate
      responses:
        '200':
          description: Au fost returnate agentii
          schema:
            type: array
            items:
              $ref: "#/definitions/Agency"
        '404':
          description: Nu s-au gasit agentii in apropiere
        '409':
          description: Informatii lipsa
  '/ticketTracking/details/{serviceId}/{agencyId}':
    get:
      tags:
        - info
      operationId: getServiceAgencyDetails
      summary: Returneaza starea bonurilor de la serviciul si agentia selectata
      produces:
        - application/json
      parameters:
        - name: serviceId
          in: path
          required: true
          type: integer
          format: int64
          description: id-ul serviciului general din tabela de mapare interna
        - name: agencyId
          in: path
          required: true
          type: integer
          format: int64
          description: id-ul agentiei selectate
        - name: ticketId
          in: query
          required: false
          type: string
          description: tichetul care se urmareste
      responses:
        '200':
          description: Au fost returnate detaliile
          schema:
              $ref: "#/definitions/ServiceMetrics"
        '404':
          description: Nu exista statistici disponibile
        '409':
          description: Informatii lipsa                        
  '/agencies/{agencyId}':
    put:
      tags:
        - stare
      summary: Actualizeaza agentia.
      operationId: updateAgency
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: agencyId
          in: path
          required: true
          type: string
        - name: agency
          in: body
          required: true
          schema:
            $ref: '#/definitions/Agency'
          description: Starea agentiei
      responses:
        '200':
          description: Agentia a fost actualizata
        '404':
          description: Agentie inexistenta
        '409':
          description: Informatii lipsa
  '/agencies/{agencyId}/services/{serviceId}/tickets':
    post:
      tags:
        - activitate
      summary: Creaza bon
      operationId: createTicket
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: agencyId
          in: path
          required: true
          type: string
        - name: serviceId
          in: path
          required: true
          type: string
        - name: ticket
          in: body
          required: true
          schema:
            $ref: '#/definitions/Ticket'
          description: Continutul bonului
      responses:
        '200':
          description: Bonul a fost creat
        '404':
          description: Agentie inexistenta sau serviciu inexistent
        '409':
          description: Informatii lipsa
  '/agencies/{agencyId}/services/{serviceId}/tickets/{ticketNo}':
    patch:
      tags:
        - activitate
      summary: Actualizeaza (partial) bonul
      operationId: updateTicket
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: agencyId
          in: path
          required: true
          type: string
        - name: serviceId
          in: path
          required: true
          type: string
        - name: ticketNo
          in: path
          required: true
          type: string
        - name: ticket
          in: body
          required: true
          schema:
            $ref: '#/definitions/Ticket'
          description: Continutul bonului
      responses:
        '200':
          description: Bonul a fost actualizat
        '404':
          description: Agentie inexistenta, serviciu inexistent sau bon inexistent
        '409':
          description: Schimbarile indicate nu pot fi efectuate (e.g., ticketNo, issueDateTime, serviceId)
definitions:
  Agency:
    type: object
    required:
      - id
      - name
      - description
      - services
      - desks
    properties:
      id:
        type: string
        description: Id-ul agentiei, ca locatie fizica (de exemplu, spcrpciv.bucuresti.pipera)
      name:
        type: string
        description: Numele scurt al agentiei (de exemplu, SPCRPCIV București)
      description:
        type: string
        description: Numele complet al agentiei (de exemplu, Serviciul Public Comunitar Regim Permise de Conducere și Înmatriculari Vehicule al Municipiului București)
      address:
        type: string
        description: Adresa agentiei, ca locatie fizica (de exemplu, Șoseaua Pipera 49, București 014254))
      location:
        $ref: '#/definitions/Location'
        description: Coordonatele GPS ale agentiei
      categories:
        type: array
        items:
          $ref: '#/definitions/Category'
        description: Categoriile de servicii oferite de agentie
      services:
        type: array
        items:
          $ref: '#/definitions/Service'
        description: Serviciilor oferite de agentie si starea lor
      desks:
        type: array
        items:
          $ref: '#/definitions/Desk'
        description: Ghiseelor agentiei si starea lor
  Category:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: string
      name:
        type: string
  GeneralService:
    type: object
    required:
      - id
      - name
      - description
      - onlyOnHomeAddress 
    properties:
      id:
        type: string
        description: Id-ul serviciului general ca denumire (din tabela de mapare interna)
      name:
        type: string
        description: Numele serviciului
      description:
        type: string
        description: descrierea serviciului - cea care trebuie sa apara sub nume
      iconLink:
        type: string
        description: link-ul catre pictograma serviciului
      onlyOnHomeAddress:
        type: boolean
        description: Marcheaza daca serviciul este arondat (se poate face doar la o agentie de la adresa din buletin) sau nu    
  Service:
    type: object
    required:
      - id
      - name
      - workingHours
      - lastIssuedTicket
    properties:
      id:
        type: string
        description: Id-ul serviciului
      name:
        type: string
        description: Numele serviciului
      categoryIds:
        type: array
        items:
          type: string
        description: Categoriile asociate serviciului
      workingHours:
        type: array
        items:
          $ref: '#/definitions/ServiceSchedule'
        description: Programul serviciului
      ticketLimit:
        type: string
        description: Numarul ultimului bon care se poate emite azi
      lastIssuedTicket:
        type: string
        description: Ultimul bon emis
  ServiceMetrics:
    type: object
    required:
      - ticketsInQueue
    properties:
      ticketsInQueue:
        type: integer
        format: int64
        description: Numarul de bonuri in asteptare
      averageWaitingTime:
        type: integer
        format: int64
        description: Timpul mediu de asteptare in minute
      averageProcessingTime:
        type: integer
        format: int64
        description: Timpul mediu de procesare (in minute) al unui tichet
      availableTickets:
        type: integer
        format: int64
        description: Cate bonuri se mai pot emite in ziua respectiva pt acel serviciu
      ticketMetrics:
        schema:
          $ref: '#/definitions/Ticket'       
  Desk:
    type: object
    required:
      - id
      - name
      - ticketsInProgress
    properties:
      id:
        type: string
      name:
        type: string
      ticketsInProgress:
        type: array
        items:
          $ref: '#/definitions/Ticket'
        description: Bonurile aflate in lucru
  Ticket:
    type: object
    required:
      - ticketNo
      - issueDateTime
      - status
      - serviceId
    properties:
      ticketNo:
        type: string
      issueDateTime:
        type: string
        format: 'date-time'
        description: Data si timpul emiterii
      status:
        $ref: '#/definitions/TicketStatus'
      serviceId:
        type: string
        description: Serviciul pentru care a fost emis bonul
      deskIds:
        type: array
        items:
          type: integer
          format: int64
        description: Ghiseele care pot procesa bonul
      estimatedProcessTime:
        type: string
        format: 'date-time'
        description: Ora estimata la care se va procesa bonul
      ticketsAhead:
        type: integer
        format: int64
        description: Numarul de bonuri emise anterior bonului in cauza si neprocesate
      averageWaitingTime:
        type: integer
        format: int64
        description: Timpul mediu de asteptare (in minute) pentru bonul in cauza
      averageProcessingTime:
        type: integer
        format: int64
        description: Timpul mediu de procesare (in minute) al bonului in cauza
  TicketStatus:
    type: string
    enum:
      - issued
      - in_progress
      - suspended
      - solved
    description: Stari posibile pentru un bon
  ServiceSchedule:
    type: object
    properties:
      dayOfWeek:
        $ref: '#/definitions/DayOfWeek'
      start:
        type: string
        format: 'date-time'
        description: De la
      end:
        type: string
        format: 'date-time'
        description: Pana la
      desks:
        type: array
        items:
          $ref: '#/definitions/Desk'
        description: Id-uri ghisee la care e arondat serviciul
  DayOfWeek:
    type: string
    enum:
      - monday
      - tuesday
      - wednesday
      - thursday
      - friday
      - saturday
      - sunday
    description: Zilele saptamanii
  Location:
    type: object
    required:
      - lat
      - lng
    properties:
      lat:
        type: number
        format: float
        description: Latitudine
      lng:
        type: number
        format: float
        description: Longitudine