language: java
jdk: oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: heroku
  api_key:
    secure: VFmGK+QeTiD3MhhaeD4uBLQZkqcRIw72oXZCwGjufF8M7LdaWhWMqvrXf9TSCxOZcEv2QLqOJIrcZUgOTLg93BmpdQ+7NUG23o5F2br3lxl0MrfS0kEiwGSH5j5FoSdm/1hirlykaNlhixek0HHeDFQWhn/Xt9GPfVcPbk+223Eh7DUO5UUMaLzvcWZtVHy0Rv3nZFecmG9txNyOSoWIIgvB6GqE5vcjb7Vhe6FRuez2swbzZn+MqGmETKXUBQ7/yDPvntVWVkVyDZDtiqdzxHbaXRn8EI5UgLsg7m/usRfCw/Ib/8ahtKEKJHB39B581CaIY+0sVVj1gflSa6X0i44kSxHXDHc36wr8eK8AMvr0JKoIflK3ecSkm1S4Wp9U/wUkaY6NIAMVB0+GSudRBDzp0L5/zKhQuBf+ASjE42+FRP2g/6oz1Tv+WDzZevCA6bIkHtwz/0gIAlf3O/6fRcrobDsmy26D3ud9sQpYpYccBllCnm+OGjBGS+euYKW0gXvmJycM4StfuT/uOpE3cNJcgR2OYzYdsxS+4a4AVL+9NZ6BlvZSsVNFpNU3mgKSEbY0K2V9DFoiZLrdC6GndtQyIOFDs675tcqxjRt86nuGOKOS/P19qZmfbwYvwGEYNwi/4DuK1uWPGjzMAAdkAh87kPHQchqtUh05mtZPiag=
  app: yoyosan-stopcozi-api
  on:
    repo: yoyosan/StopCozi-api
